# Generated by Django 2.0.2 on 2018-02-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0003_auto_20180124_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalobjective',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='okr.Team'),
        ),
    ]
