# Generated by Django 2.0.2 on 2018-02-25 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0005_auto_20180208_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='coin_value',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tmp_status',
        ),
    ]
