# Generated by Django 2.0.2 on 2018-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0006_auto_20180225_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(
                choices=[('Modified Objective', 'Modified Objective'), ('Modified Key Result', 'Modified Key Result'),
                         ('Deleted Objective', 'Deleted Objective'), ('Deleted Key Result', 'Deleted Key Result'),
                         ('Created Objective', 'Created Objective'), ('Created Key Result', 'Created Key Result'),
                         ('Completed Objective', 'Completed Objective'),
                         ('Completed Key Result', 'Completed Key Result'),
                         ('Completed JIRA issue.', 'Completed JIRA issue.')], max_length=100),
        ),
    ]
