# Generated by Django 2.0.2 on 2018-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0008_auto_20180307_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='percentage',
            new_name='complete_percentage',
        ),
        migrations.AddField(
            model_name='objective',
            name='incomplete_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='objective',
            name='null_percentage',
            field=models.FloatField(default=0),
        ),
    ]
