# Generated by Django 2.0.2 on 2018-03-28 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('okr', '0010_auto_20180308_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cardpicked', models.CharField(max_length=255)),
                ('story', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='user_poker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poker',
                'verbose_name_plural': 'Pokers',
            },
        ),
    ]
