# Generated by Django 2.0.2 on 2018-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0011_poker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='poker',
            options={'verbose_name': 'Poker', 'verbose_name_plural': 'Poker'},
        ),
    ]
