# Generated by Django 2.0.2 on 2018-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okr', '0012_auto_20180405_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poker',
            name='message',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
